### ISSUE TITLE
Jetpack compose crash

### ISSUE THREAD

**Issue by jcfrk101** [ionic-team/ionic-portals-android#33]
`java.lang.ClassCastException:` androidx.compose.ui.tooling.PreviewActivity cannot be cast to androidx.appcompat.app.AppCompatActivity
                                                                                                    	at io.ionic.portals.PortalView.loadPortal(PortalView.kt:79)
                                                                                                    	at io.ionic.portals.PortalView.<init>(PortalView.kt:41)
                                                                                                    	at io.ionic.portals.PortalView.<init>(PortalView.kt:34)
                                                                                                    	at com.terra.app.MainActivityKt$MainContent$1$1$1.invoke(MainActivity.kt:62)
                                                                                                    	at com.terra.app.MainActivityKt$MainContent$1$1$1.invoke(MainActivity.kt:61)`

**Comment by jcfrk101** [comment]
Just to add context this also occurs with MainActivity

    java.lang.ClassCastException: com.terra.app.MainActivity cannot be cast to androidx.appcompat.app.AppCompatActivity

**Comment by carlpoole** [comment]
Hi there. The way Portals currently works it needs the containing activity to be an extension of `AppCompatActivity()` since it uses Fragments. From the errors you posted it seems like this may not be the case. Are you able to make the containing activity extend `AppCompatActivity()` and see if that fixes your issue?
